### ISSUE TITLE
createdAtBlockNumber contains false data

### ISSUE THREAD

**Issue by TimDaub** [spinamp/web3-music-subgraph#15]
I'm querying the following:

```
query {
  nfts(first: 1000, where: { 
    createdAtBlockNumber_lt: 14323199, 
    createdAtBlockNumber_gte: 14304318 }) {
    id,
    createdAtBlockNumber
  }
}
```

and my results look like this:

```
{
  "data": {
    "nfts": [
      {
        "id": "0x1a387136fcde3a82b0a6629fc64982de535cd406/1",
        "createdAtBlockNumber": "14316604"
      },
...
]
```

You can try it yourself here: https://api.thegraph.com/subgraphs/name/timdaub/web3musicsubgraph/graphql

However, at least for the first nft, I believe the `createdAtBlockNumber` field is incorrect. If we do some research on Etherscan for 0x1a387136fcde3a82b0a6629fc64982de535cd406, we find that this NFT was created at a different block: https://etherscan.io/tx/0xb1918ca04a829ff1712025a57e5cb42f0fb6cbab8a0955b3b5ed83fe27a90420 at block number [14323199](https://etherscan.io/block/14323199)

**Comment by musnit** [comment]
@TimDaub the above etherscan link you shared doesn't match the nft: 0x1a387136fcde3a82b0a6629fc64982de535cd406/1 -> https://etherscan.io/tx/0x21de92547f428615bbc62417270e3bda711b5a20e27fa0490332abb1a00b71ad which is at block 14316604.

is there another example you meant to refer to? it could be that the createdAtBlockNumber is being replaced on each transfer rather than just on the mint, though I'm not really maintaining this repo anymore.
